config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'portfolio_pages/home'

  get '/portfolio' => 'portfolio_pages#portfolio', as: :portfolio
  get '/projects'  => 'portfolio_pages#projects',  as: :projects
  get '/resume'    => 'portfolio_pages#resume',    as: :resume
  get '/resume-pdf'=> 'portfolio_pages#resume_pdf',as: "resume-pdf"

  get '/contact'  => 'contacts#new',               as: :contact
  resources :contacts, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      resources :user_contacts, only: [:index, :create, :destroy, :update]
    end
  end

  resources :demo, only: [:index]
  

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject,   :validate => true
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => %("Message from Portfolio: #{subject}"),
        :to => "raminder.goraya@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user_contact.rb
class UserContact < ActiveRecord::Base
  def self.search(search)
    where("lower(name) LIKE ?", "%#{search.downcase}%")
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController 
  respond_to :json 
end

app/controllers/api/v1/user_contacts_controller.rb
class Api::V1::UserContactsController < Api::V1::BaseController

  before_action :add_cors_to_json

  def index
    if params[:search]
      respond_with UserContact.search(params[:search]).order(params[:order])
    else
      respond_with UserContact.all.order(params[:order])
    end
  end

  def show
  end

  # GET /user_contacts/new
  def new
    @user_contact = UserContact.new
  end

  # GET /user_contacts/1/edit
  def edit
  end

  def create
    respond_with :api, :v1, UserContact.create(user_contact_params)
  end

  def update
    user_contact = UserContact.find(params["id"])
    user_contact.update_attributes(user_contact_params)
    respond_with user_contact, json: user_contact
  end

  def destroy
    respond_with UserContact.destroy(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_contact
      @user_contact = UserContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_contact_params
      params.require(:user_contact).permit(:name, :job_title, :address, :phone_number, :email)
    end

    def add_cors_to_json
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
      headers['Access-Control-Request-Method'] = '*'
      headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    #@contact.request = request

    respond_to do |format|
      if @contact.deliver
        format.json { render json: @contact, status: :created }
      else
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end

  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end
end

app/controllers/portfolio_pages_controller.rb
class PortfolioPagesController < ApplicationController
  def home
  end

  def portfolio
    @page_title = "Portfolio"
  end

  def projects
    @page_title = "Projects"
    # github       = Github.new basic_auth: "#{Rails.configuration.github[:username]}:#{Rails.configuration.github[:password]}"
    github       = Github.new do |config|
      config.basic_auth         = "#{Rails.configuration.github[:username]}:#{Rails.configuration.github[:password]}"
      config.connection_options = {headers: {"X-GitHub-OTP" => '2fa token'}}
    end
    @git_repos   = github.repos.list user: 'rgoraya'
    @git_profile = github.users.get  user: 'rgoraya'

    # bitbucket   = BitBucket.new login: Rails.configuration.bitbucket[:username], password: Rails.configuration.bitbucket[:password]
    # @bit_repos   = bitbucket.repos.list
    # @bit_profile = bitbucket.user_api.profile.user

    # @repo_types = [ { :repo_type => "Github", :repos => @git_repos.to_a }, { :repo_type => "BitBucket", :repos => @bit_repos } ]

    @repo_types = [ { :repo_type => "Github", :repos => @git_repos.to_a } ]

  end

  def resume
    @page_title = "Resume"
  end

  def resume_pdf
    request.format = "pdf" unless params[:format]
    @page_title = "Resume PDF"
    respond_to do |format|
      format.pdf do
        render :pdf    => "raminder_goraya",
               :disposition => "inline",
               :layout      => "pdf_document.html.haml"
      end

      format.html
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @page_title = "Welcome"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def body_class_name
    "#{controller_name}_#{action_name}"
  end

  def page_title
    "Raminder Goraya#{@page_title ? " | " + @page_title : ""}"
  end

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

  def abbr(abbr, full_form)
    content_tag(:abbr, :title => full_form) do
      abbr
    end
  end

  def meta_description
    "Raminder Goraya's portfolio. An experienced software engineer, passionate about developing web and mobile apps offering creative and responsive user interfaces, powered by robust and efficient back-end."
  end

end

app/helpers/portfolio_pages_helper.rb
module PortfolioPagesHelper

  def project_type_logo(repository_type)
    if repository_type == "Github"
      "portfolio/github_logo.png"
    elsif repository_type == "BitBucket"
      "portfolio/bitbucket_logo.png"
    end
  end

end

app/helpers/user_contacts_helper.rb
module UserContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.js.erb
console.log("create.js.erb file");

// add new comment to end of comments section
$("#message")
        .removeClass('hidden')
        .find('.text').html("Dear <%= @name %> your message has been delivered!")

$("#new_contact").trigger("reset");

app/views/contacts/new.html.haml
.container

  #message.alert
    %span.text
    %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} &times;

  .p-0.rounded.position-relative.postal-border-container.shadow-sm
    .postal-border
    .postal-border.vertical.left.d-none.d-md-block
    .postal-border.vertical.right.d-none.d-md-block
    .row.m-4
      .col-lg-8.margin-bottom-20
        %h2.font-26.margin-bottom-30
          Say Hello!
        = simple_form_for @contact, :html => { :class => '', "data-remote" => true, "data-type" => :json } do |f|
          = f.input :name, :required => true, :placeholder => "Please enter your name"
          = f.input :email, :required => true, :placeholder => "abc@example.com"
          = f.input :subject, :required => true
          = f.input :message, :as => :text, :required => true, :rows => 5
          .hidden
            = f.input :nickname, :hint => 'Leave this field blank!'
          %div
            = f.button :submit, 'Send message', :class=> "btn btn-outline-dark"


      #all_badges.col-lg-4.text-center.margin-top-20
        %script{async: "", defer: "defer", src: "https://platform.linkedin.com/badges/js/profile.js", type: "text/javascript"}
        #linkedIn.badge-container.margin-bottom-20
          .badge-base.LI-profile-badge{"data-locale" => "en_US", "data-size" => "medium", "data-theme" => "dark", "data-type" => "VERTICAL", "data-vanity" => "rgoraya", "data-version" => "v1"}
          - #   %a.badge-base__link.LI-simple-link{href: "https://www.linkedin.com/in/rgoraya?trk=profile-badge"} Raminder G.
    .postal-border

= render :partial => "shared/back_to_top"

app/views/demo/index.html.haml
= react_component("ContactsApp", { view: "view_all", contacts:[] }, { class: "container", id: "contacts_app" }) 

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render "shared/meta"
    = stylesheet_link_tag "application", params[:controller], :media => "all", 'data-turbolinks-track' => true
    = javascript_include_tag "application", "#{controller_name}_#{action_name}", 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.css", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :src => "https://kit.fontawesome.com/80daf764fb.js"}

  %body{ :class => body_class_name }
    #pageContainer.container-fluid
      = render "shared/header"
      #content
        = yield
      = render "shared/footer"

app/views/layouts/pdf_document.html.haml
!!!
%html
  %head
    = render "shared/meta"
    = wicked_pdf_stylesheet_link_tag "pdf_document"
  %body{ :class => body_class_name }
    = render "shared/resume_header"
    = yield

app/views/mail_form/contact.html.haml
%div{:marginheight => "0", :marginwidth => "0", :style => "margin:0;padding:0;min-height:100%;width:100%"}
  %table{:style => "width: 920px; background-color: #fcfcfc; border: 0; font-family: Verdana, Arial, sans-serif", :align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0"}
    %tr
      %td{:style => "font-size:0; line-height:0;", :colspan => 3, :height => 20}
    %tr
      %td{ :colspan => 3, :style => "line-height: 40px" }
        = cl_image_tag("portfolio/airmail_stripe.png", :width => 920, :height => 20, :crop => :fit)
    %tr
      %td{:style => "font-size:0; line-height:0;", :colspan => 3, :height => 20}
    %tr
      %td{:colspan => 3, :style => "line-height: 40px"}
        %h2{ :style => "font-size: 22px; text-align: center"} Raminder! You've got mail.

    - @resource.mail_form_attributes.each do |attribute, value|
    - next if value.blank?
      %tr
        %td{:style => "line-height: 20px"}
          = @resource.class.human_attribute_name(attribute)
        %td{:style => "line-height: 20px"}
          = value
    %tr
      %td{:style => "font-size:0; line-height:0;", :colspan => 3, :height => 20}
    %tr
      %td{ :colspan => 3, :style => "line-height: 40px" }
        = cl_image_tag("portfolio/airmail_stripe.png", :width => 920, :height => 20, :crop => :fit)
    %tr
      %td{:style => "font-size:0; line-height:0;", :colspan => 3, :height => 20}

app/views/portfolio_pages/home.html.haml
%h1 PortfolioPages#home
%p Find me in app/views/portfolio_pages/home.html.haml

app/views/portfolio_pages/projects.html.haml
.container
  %h3.my-3
    Repositories

  #github_projects
    #projectBlocks.col-xs-12.padding-0.block-container
      .flex-wrap.d-flex
        - bg_classes = [ 'bg-portfolio', 'bg-resume', 'bg-pale-coral', 'bg-contact', 'bg-projects']
        - index = 0
        - @repo_types.each do |repo_type|
          - repo_type[:repos].each do |repo|
            - index += 1
            - modulo_idx = index >= bg_classes.length ? (index % bg_classes.length) : index
            - bg_class = bg_classes[modulo_idx]
            - private = repo[:is_private] || repo[:private]
            - website = repo[:homepage] || repo[:website]
            .col-xs-12.col-sm-6.p-0.d-flex
              .project-block.color-ghost-white.card.p-0.rounded-0{ :class => "#{bg_class}"}
                %h3.font-weight-light.card-header.px-4.py-3
                  -# = cl_image_tag(project_type_logo(repo_type[:repo_type]), :width => 60, :height => 60, :crop => :fill)
                  %i.fab.fa-github 
                  = repo["name"]
                %p.card-body.p-4.m-0
                  = repo["description"]
                .d-flex.justify-content-between.card-footer.px-4.py-3
                  %a.color-ghost-white{:href => "#{private ? '#' : repo['html_url']}"}
                    #{repo_type[:repo_type]} Repository
                    - if private
                      %i.glyphicon.glyphicon-lock
                      (private)
                  - unless website.blank?
                    %a.text-right.color-ghost-white{:href => "#{private ? '#' : repo[:homepage]}"}
                      Website

  %h3.my-3
    Profiles

  #profiles
    #profileBlocks
      .flex-wrap.d-flex
        .col-xs-12.col-sm-6.p-0
          .profile-block.color-ghost-white.bg-pale-blue.card.p-0.rounded-0
            %h3.font-weight-light.card-header.px-4.py-3
              -# = cl_image_tag("portfolio/github_logo.png", :width => 60, :height => 60, :crop => :fit)
              %i.fab.fa-github 
              Github
            .card-body.p-4.m-0
              %a.color-ghost-white{ :href => "#{@git_profile['html_url']}" }
                = @git_profile['html_url']
        .col-xs-12.col-sm-6.p-0
          .profile-block.color-ghost-white.bg-pale-coral.card.p-0.rounded-0
            %h3.font-weight-light.card-header.px-4.py-3
              -# = cl_image_tag("portfolio/bitbucket_logo.png", :width => 60, :height => 60, :crop => :fit)
              %i.fab.fa-bitbucket 
              BitBucket
            .card-body.p-4.m-0
              %a.color-ghost-white{ :href => "https://bitbucket.org/rsgoraya/" }
                = "https://bitbucket.org/rsgoraya/"


= render "shared/back_to_top"

app/views/portfolio_pages/resume_pdf.pdf.haml
= render :template => "portfolio_pages/resume.html.haml"

app/views/shared/_back_to_top.html.haml
%a#back_to_top.color-ghost-white.margin-0.text-center.rounded-circle{:href => "#top", :'data-spy' => "affix", :'data-offset-top' => "100" }
  %i.glyphicon.glyphicon-triangle-top

app/views/shared/_footer.html.haml
#footer.container-fluid.width100p
  .container.text-center
    Copyright &#169; #{Time.zone.now.year} Raminder Goraya

app/views/shared/_header.html.haml
#header
  %nav.navbar.container.margin-bottom-0.navbar-expand-lg
    .navbar-header.mr-auto
      .navbar-brand
        %a#name.clearfix{ :href => root_path }
          #rCircle.float-left.rounded-circle.font-20.color-ghost-white.text-center r
          #myName.float-left.font-20 aminder goraya
    %button.navbar-toggler{"data-target" => "#rgorayaNavbar", "data-toggle" => "collapse", :type => "button"}
      %span.oi.oi-menu
    #rgorayaNavbar.collapse.navbar-collapse.justify-content-end
      %ul.nav.navbar-nav
        = nav_link 'Home', root_path
        = nav_link 'Portfolio', portfolio_path
        = nav_link 'Projects', projects_path
        = nav_link 'Resume', resume_path
        = nav_link 'Contact', contact_path
  .d-none.d-sm-block.p-2

app/views/shared/_meta.html.haml
%meta{ :charset => "utf-8" }
%title= page_title
%meta{ :name => "title", :content => page_title }
%meta{ :name => "description", :content => meta_description }
%meta{:content => "software engineer, React, San Francisco, silicon valley, uc irvine, ruby on rails, front-end, experienced, javascript, seo, responsive design", :name => "keywords"}/
%meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
%meta{ :name => "author", :content => "rgoraya.com" }
= favicon_link_tag

app/views/shared/_resume_header.html.haml
.container
  .row
    .col-md-6
      %h1
        Raminder Goraya
    .col-md-6
      .text-right
        #{link_to root_url root_url}
        %br
        Palo Alto, CA

app/views/user_contacts/_form.html.haml
= simple_form_for(@user_contact) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :job
    = f.input :title
    = f.input :address
    = f.input :phone_number
    = f.input :email
    = f.input :picture

  .form-actions
    = f.button :submit

app/views/user_contacts/edit.html.haml
%h1 Editing user_contact

= render 'form'

= link_to 'Show', @user_contact
\|
= link_to 'Back', user_contacts_path

app/views/user_contacts/index.html.haml
%h1 Listing user_contacts

%table
  %thead
    %tr
      %th Name
      %th Job
      %th Title
      %th Address
      %th Phone number
      %th Email
      %th Picture
      %th
      %th
      %th

  %tbody
    - @user_contacts.each do |user_contact|
      %tr
        %td= user_contact.name
        %td= user_contact.job
        %td= user_contact.title
        %td= user_contact.address
        %td= user_contact.phone_number
        %td= user_contact.email
        %td= user_contact.picture
        %td= link_to 'Show', user_contact
        %td= link_to 'Edit', edit_user_contact_path(user_contact)
        %td= link_to 'Destroy', user_contact, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User contact', new_user_contact_path

app/views/user_contacts/new.html.haml
%h1 New user_contact

= render 'form'

= link_to 'Back', user_contacts_path

app/views/user_contacts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user_contact.name
%p
  %b Job:
  = @user_contact.job
%p
  %b Title:
  = @user_contact.title
%p
  %b Address:
  = @user_contact.address
%p
  %b Phone number:
  = @user_contact.phone_number
%p
  %b Email:
  = @user_contact.email
%p
  %b Picture:
  = @user_contact.picture

= link_to 'Edit', edit_user_contact_path(@user_contact)
\|
= link_to 'Back', user_contacts_path

app/views/welcome/index.html.haml
.container
  .row.clearfix
    .col-xs-12.col-sm-12.margin-bottom-30
      %h1.font-28
        Hi! I'm Raminder.
      %p.font-16.padding-top-10
        A <b>hands-on Engineering Leader</b> with experience in driving <b>Engineering Strategy</b> and <b>Product Vision</b> for products serving 
        <b>millions of customers</b>. 
      %p
        Passionate about <b>building engineering teams</b> from ground up as well as <b>growing current teams</b> and helping organizations <b>build 
        high quality software</b> from scratch and <b>revive failing products</b> through simplification, appropriate changes to business or 
        implementation strategies, partial or complete re-design and re-architecture. 
  .row
    .d-none.d-sm-block.col-sm-2
    #menuBlocks.col-xs-12.col-sm-12
      .row.clearfix
        .col-xs-12.col-md-4
          -# .d-none.d-sm-block.padding-15
          %a.menu-block.portfolio.color-ghost-white.padding-30{ :href => portfolio_path}
            %h2.font-26
              %i.fa.fa-road
              Portfolio
            %p.margin-bottom-20 My growth story, from <b>Frontend Engineering</b> to <b>Product</b> to <b>Engineering Management</b>.
        -# .col-xs-12.col-sm-6
        -#   %a.menu-block.projects.color-ghost-white.padding-20{ :href => projects_path}
        -#     %h2.font-26
        -#       %i.fa.fa-terminal
        -#       Projects
        -#     %p.margin-bottom-20 Current and past projects and my public repositories

        -# .row.clearfix
        .col-xs-12.col-md-4
          -# .d-none.d-sm-block.padding-15
          %a.menu-block.resume.color-ghost-white.padding-30{ :href => resume_path }
            %h2.font-26
              %i.fa.fa-file
              Résumé
            %p.margin-bottom-20 
              My full professional résumé, built responsive to printing and downloadable as PDF.
        .col-xs-12.col-md-4
          -# .d-none.d-sm-block.padding-15
          %a.menu-block.contact.color-ghost-white.padding-30{ :href => contact_path}
            %h2.font-26
              %i.fa.fa-address-book
              Contact
            %p.margin-bottom-20 Say Hello! I'm eager to meet other members of our vibrant tech community.
    .row.margin-top-30.margin-bottom-30
      .d-none.d-md-block.col-md-1
      #tag-cloud.col-sm-12.col-md-10.font-normal
      :javascript
        // Sample skills array
        let skills = [
            { name: "JavaScript", value: 110 },
            { name: "HTML", value: 100 },
            { name: "CSS", value: 100 },
            { name: "React", value: 95 },
            { name: "Technical Leadership", value: 110 },
            { name: "Engineering Management", value: 95 },
            { name: "Microservices", value: 80 },
            { name: "Strategy", value: 95 },
            { name: "Enterprise Architecture", value: 95 },
            { name: "Enterprise Software", value: 95 },
            { name: "SEO", value: 87 },
            { name: "Hiring", value: 95 },
            { name: "Software Project Management", value: 80 },
            { name: "SQL", value: 80 },
            { name: "System Design", value: 85 },
            { name: "Product Management", value: 75 },
            { name: "Talent Development", value: 80 },
            { name: "Continuous Improvement", value: 70 },
            { name: "Stakeholder Management", value: 87 },
            { name: "Budgeting", value: 72 },
            { name: "Vendor Management", value: 78 },
            { name: "AWS", value: 85 },
            { name: "Ruby on Rails", value: 95 },
            { name: "Redux", value: 80 },
            { name: "Databases", value: 80 },
            { name: "Ruby", value: 90 },
            { name: "OKRs", value: 92 },
            { name: "TypeScript", value: 76 }
        ];

        // Function to shuffle skills
        function shuffle(arr) {
          let currentIndex = arr.length;

          // While there remain elements to shuffle...
          while (currentIndex != 0) {

            // Pick a remaining element...
            let randomIndex = Math.floor(Math.random() * currentIndex);
            currentIndex--;

            // And swap it with the current element.
            [arr[currentIndex], arr[randomIndex]] = [
              arr[randomIndex], arr[currentIndex]];
          }
          return arr;
        }
        // Function to generate a random color
        function getRandomColor() {
            //const letters = '0123456789ABCDEF';
            const colors = ["#a4b6dd", "#d09292", "#c094cc", "#a2d0c0", "#c37892", "#e79796", "#556c75", "#997b66", "#b58463", "#336b8b", "#83984d", "#9e8189"];
            
            return colors[Math.floor(Math.random() * colors.length)]
            //let color = '#';
            //for (let i = 0; i < 6; i++) {
            //    color += letters[Math.floor(Math.random() * 16)];
            //}
            //return color;
        }

        // Function to generate the tag cloud
        function generateTagCloud(skills) {
            const tagCloudContainer = document.getElementById('tag-cloud');

            // Find the minimum and maximum skill values
            const minValue = Math.min(...skills.map(skill => skill.value));
            const maxValue = Math.max(...skills.map(skill => skill.value));

            skills.forEach(skill => {
                const tag = document.createElement('span');
                tag.className = 'tag';
                tag.textContent = skill.name;

                // Set the font size relative to the skill value
                const fontSize = ((skill.value - minValue) / (maxValue - minValue) * 25) + 15; // Adjust 10 and 20 as needed
                tag.style.fontSize = `${fontSize}px`;

                // Set a random color
                tag.style.color = getRandomColor();

                tagCloudContainer.appendChild(tag);
            });
        }

        // Generate the tag cloud on page load
        document.addEventListener('DOMContentLoaded', () => generateTagCloud(shuffle(skills)));

    .d-none.d-sm-block.col-sm-2

= render "shared/back_to_top"